export const rooms = [
  {
    slug: 'glen-suite',
    name: 'The Glen Suite',
    type: 'Suite',
    sqm: 65,
    occupancy: 2,
    floor: 'First Floor',
    view: 'Glen & Mountain',
    rate: 495,
    description:
      'Our most spacious accommodation, the Glen Suite commands sweeping views across the Perthshire highlands. A freestanding copper bath, king four-poster, and private sitting room make this the definitive highland sanctuary.',
    shortDescription: 'Our flagship suite with panoramic glen views and a freestanding copper bath.',
    image: 'https://images.pexels.com/photos/1579253/pexels-photo-1579253.jpeg?w=1200&q=80',
    gallery: [
      'https://images.pexels.com/photos/1579253/pexels-photo-1579253.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg?w=1200&q=80',
    ],
    amenities: [
      'King four-poster bed',
      'Freestanding copper bath',
      'Monsoon shower',
      'Private sitting room',
      'Wood-burning stove',
      'Original artwork',
      'Nespresso machine',
      'Bose sound system',
      'WiFi',
      'Smart TV',
    ],
    featured: true,
  },
  {
    slug: 'loch-room',
    name: 'Loch Room',
    type: 'Deluxe',
    sqm: 42,
    occupancy: 2,
    floor: 'Ground Floor',
    view: 'Loch & Woodland',
    rate: 325,
    description:
      'A deeply calm room with direct views across the estate loch. Dressed in storm blue linens and warm oak, the Loch Room offers a private terrace for early morning mist and evening drams.',
    shortDescription: 'Serene loch views with a private terrace, storm-blue interiors.',
    image: 'https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?w=1200&q=80',
    gallery: [
      'https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?w=1200&q=80',
    ],
    amenities: [
      'King bed',
      'Roll-top bath',
      'Walk-in shower',
      'Private terrace',
      'Handcrafted oak furniture',
      'Nespresso machine',
      'Smart TV',
      'WiFi',
      'Bathrobe & slippers',
    ],
    featured: true,
  },
  {
    slug: 'moorland-room',
    name: 'Moorland Room',
    type: 'Classic',
    sqm: 32,
    occupancy: 2,
    floor: 'Second Floor',
    view: 'Heather Moorland',
    rate: 245,
    description:
      'Elevated above the estate, the Moorland Room frames an uninterrupted view across purple heather and open sky. Warm tweeds, a deep bath, and hand-painted botanical wallpaper create an intimate highland haven.',
    shortDescription: 'Classic highland character with heather moorland views.',
    image: 'https://images.pexels.com/photos/1183434/pexels-photo-1183434.jpeg?w=1200&q=80',
    gallery: [
      'https://images.pexels.com/photos/1183434/pexels-photo-1183434.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?w=1200&q=80',
    ],
    amenities: [
      'King or twin beds',
      'Deep soaking bath',
      'Rainfall shower',
      'Botanical wallpaper',
      'Reading nook',
      'Nespresso machine',
      'Smart TV',
      'WiFi',
    ],
    featured: true,
  },
  {
    slug: 'birch-room',
    name: 'The Birch Room',
    type: 'Classic',
    sqm: 28,
    occupancy: 2,
    floor: 'First Floor',
    view: 'Birch Woodland',
    rate: 215,
    description:
      'Light filters through silver birch canopy into this understated, beautifully proportioned room. White linens, natural stone bathroom and locally foraged flowers in season.',
    shortDescription: 'Light-filled room overlooking ancient birch woodland.',
    image: 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?w=1200&q=80',
    gallery: [
      'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?w=1200&q=80',
    ],
    amenities: [
      'King or twin beds',
      'Natural stone bathroom',
      'Rainfall shower',
      'Writing desk',
      'Nespresso machine',
      'Smart TV',
      'WiFi',
    ],
    featured: false,
  },
  {
    slug: 'tower-suite',
    name: 'The Tower Suite',
    type: 'Suite',
    sqm: 72,
    occupancy: 2,
    floor: 'Tower',
    view: '360 Estate Panorama',
    rate: 545,
    description:
      'Occupying the full top floor of Craigmore\'s Victorian tower, this extraordinary suite offers 360-degree views of the estate. A spiral stair connects the bedroom to a private study below. The most sought-after address in Perthshire.',
    shortDescription: '360-degree views from our Victorian tower. The pinnacle of Craigmore.',
    image: 'https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?w=1200&q=80',
    gallery: [
      'https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/1631677/pexels-photo-1631677.jpeg?w=1200&q=80',
    ],
    amenities: [
      'Super-king bed',
      'Freestanding bath',
      'Dual aspect shower',
      'Private study',
      'Spiral staircase',
      'Telescope',
      'Bose sound system',
      'Nespresso machine',
      'Smart TV',
      'WiFi',
    ],
    featured: false,
  },
  {
    slug: 'garden-room',
    name: 'The Garden Room',
    type: 'Deluxe',
    sqm: 38,
    occupancy: 2,
    floor: 'Ground Floor',
    view: 'Walled Garden',
    rate: 295,
    description:
      'Step directly from your room into the walled kitchen garden. Filled with the scent of roses and herbs, this peaceful ground-floor room has a private French-door terrace onto gravel paths and clipped box hedging.',
    shortDescription: 'Direct access to the walled kitchen garden. Scent of roses included.',
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?w=1200&q=80',
    gallery: [
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?w=1200&q=80',
      'https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg?w=1200&q=80',
    ],
    amenities: [
      'King bed',
      'French doors to terrace',
      'Freestanding bath',
      'Walk-in shower',
      'Garden view',
      'Nespresso machine',
      'Smart TV',
      'WiFi',
    ],
    featured: false,
  },
];

export const experiences = [
  {
    slug: 'fly-fishing',
    name: 'Fly Fishing on the Tay',
    category: 'Field Sports',
    duration: 'Full day / Half day',
    price: 'From £180 per rod',
    seasons: ['Spring', 'Summer', 'Autumn'],
    description:
      'The River Tay is Scotland\'s most celebrated salmon river, and our gillie has 30 years of knowledge to share. Whether you\'re casting your first line or an experienced rod, we hold private beats with some of the finest lies in the country.',
    image: 'https://images.pexels.com/photos/1007628/pexels-photo-1007628.jpeg?w=800&q=80',
    includes: ['Private beat access', 'Expert gillie', 'Equipment hire available', 'Packed lunch', 'Return transport from Craigmore'],
  },
  {
    slug: 'highland-stalking',
    name: 'Red Deer Stalking',
    category: 'Field Sports',
    duration: 'Full day',
    price: 'From £350 per rifle',
    seasons: ['Autumn'],
    description:
      'Our head stalker guides you across the hill above Craigmore in pursuit of red deer. This is the authentic highland experience — physical, meditative, and deeply rooted in the land.',
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?w=800&q=80',
    includes: ['Head stalker guide', 'Vehicle transport to the hill', 'Gralloch and larder', 'Venison to take home', 'Certificate'],
  },
  {
    slug: 'whisky-tasting',
    name: 'Private Whisky Tasting',
    category: 'Tasting & Dining',
    duration: '2 hours',
    price: 'From £85 per person',
    seasons: ['Spring', 'Summer', 'Autumn', 'Winter'],
    description:
      'Our whisky butler curates a personal tasting from Craigmore\'s collection of over 200 malts — with particular focus on the Perthshire distilleries of the Highland region. Tutored sessions for 2–8 guests.',
    image: 'https://images.pexels.com/photos/3407777/pexels-photo-3407777.jpeg?w=800&q=80',
    includes: ['Tutored tasting of 5 malts', 'Tasting notes', 'Water and oatcakes', 'Personalised selection recommendation'],
  },
  {
    slug: 'estate-walk',
    name: 'Guided Estate Walk',
    category: 'Outdoors',
    duration: '3 hours',
    price: 'Complimentary for guests',
    seasons: ['Spring', 'Summer', 'Autumn', 'Winter'],
    description:
      'Our head ranger leads an intimate walk through 400 acres of ancient woodland, moorland and lochside. Learn to read the land — tracks, calls, seasons, history.',
    image: 'https://images.pexels.com/photos/1486974/pexels-photo-1486974.jpeg?w=800&q=80',
    includes: ['Expert ranger guide', 'Binoculars provided', 'Field guide to take home', 'Hot flask of tea'],
  },
  {
    slug: 'foraging-cookery',
    name: 'Foraging & Cookery Class',
    category: 'Tasting & Dining',
    duration: 'Half day',
    price: 'From £120 per person',
    seasons: ['Spring', 'Summer', 'Autumn'],
    description:
      'Join our chef and estate forager on a morning walk to gather wild ingredients — then return to the kitchen to transform them into a three-course lunch. Season-led, hands-on, delicious.',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?w=800&q=80',
    includes: ['Guided foraging walk', 'Cookery class with head chef', 'Three-course lunch with wine', 'Recipe cards to take home'],
  },
  {
    slug: 'spa-treatments',
    name: 'In-Room Spa Treatments',
    category: 'Wellness',
    duration: '60 or 90 minutes',
    price: 'From £95 per treatment',
    seasons: ['Spring', 'Summer', 'Autumn', 'Winter'],
    description:
      'Our therapists come to you, using botanicals grown on the estate. Choose from deep tissue massage, Scottish seaweed wraps, or a bespoke facial using peat-purified water. The ultimate in-room indulgence.',
    image: 'https://images.pexels.com/photos/3757952/pexels-photo-3757952.jpeg?w=800&q=80',
    includes: ['In-room setup', 'Choice of treatments', 'Locally sourced botanicals', 'Post-treatment tea'],
  },
];

export const testimonials = [
  {
    id: 1,
    quote:
      'Craigmore House is everything the highlands should be — wild, beautiful, and looked after with extraordinary care. The Glen Suite is our annual pilgrimage.',
    guestName: 'Sarah & James W.',
    roomStayed: 'The Glen Suite',
    rating: 5,
    date: 'October 2024',
  },
  {
    id: 2,
    quote:
      'The food alone is worth the journey. Chef Mackenzie\'s tasting menu reads like a love letter to Perthshire. We\'ve stayed in six rooms now and each one is better than the last.',
    guestName: 'Thomas R.',
    roomStayed: 'The Tower Suite',
    rating: 5,
    date: 'September 2024',
  },
  {
    id: 3,
    quote:
      'Nothing rushed, nothing overdone, nothing out of place. Craigmore understands that true luxury is absence — of noise, of hurry, of pretension. We cannot wait to return.',
    guestName: 'Catherine M.',
    roomStayed: 'Loch Room',
    rating: 5,
    date: 'August 2024',
  },
  {
    id: 4,
    quote:
      'The fly fishing experience was exceptional. Our gillie was patient, knowledgeable, and quietly brilliant. We caught three salmon. The packed lunch was equally memorable.',
    guestName: 'David & Helen B.',
    roomStayed: 'Moorland Room',
    rating: 5,
    date: 'July 2024',
  },
];

export const teamMembers = [
  {
    name: 'Alasdair Mackenzie',
    role: 'General Manager & Owner',
    bio: 'Alasdair returned to his family\'s ancestral estate in 2018 after twenty years in London hospitality, with a singular ambition: to create the highland hotel he\'d always dreamed of staying in. Under his tenure, Craigmore has been recognised by Condé Nast, The Sunday Times and The Guardian as one of Scotland\'s finest addresses.',
    image: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?w=400&q=80',
  },
  {
    name: 'Catriona Mackenzie',
    role: 'Head of Hospitality',
    bio: 'Catriona oversees every guest experience at Craigmore, from the first enquiry to the last farewell. Her background in luxury event management and her encyclopaedic knowledge of Perthshire make her the person every guest wishes they could pack in their luggage.',
    image: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?w=400&q=80',
  },
  {
    name: 'Finlay Ross',
    role: 'Head Chef',
    bio: 'Finlay trained under two Michelin-starred chefs before returning to Scotland to cook the land he grew up on. His menus change with the estate and the season — venison from the hill, fish from the river, vegetables from the walled garden, whisky from the glen.',
    image: 'https://images.pexels.com/photos/887827/pexels-photo-887827.jpeg?w=400&q=80',
  },
  {
    name: 'Duncan Fraser',
    role: 'Head Stalker & Ranger',
    bio: 'Duncan has worked Craigmore\'s 400 acres for over two decades, and knows every tree, track and tenant. He leads our field sports, guided walks, and the annual deer management programme — and is the most trusted source of local knowledge in the county.',
    image: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?w=400&q=80',
  },
];

export const faqs = [
  {
    question: 'What is your check-in and check-out time?',
    answer: 'Check-in is from 3pm. Check-out is by 11am. Early check-in and late check-out are available subject to availability — please enquire when booking.',
  },
  {
    question: 'Do you accept dogs?',
    answer: 'We are a dog-friendly hotel. Well-behaved dogs are welcome in selected ground-floor rooms and in the bar. We ask that dogs are kept on leads in the public gardens. A small supplement of £25 per dog per night applies.',
  },
  {
    question: 'Is there a minimum stay?',
    answer: 'During peak season (July–September) and over bank holidays, we operate a two-night minimum stay. At all other times there is no minimum.',
  },
  {
    question: 'What is your cancellation policy?',
    answer: 'Reservations cancelled more than 14 days before arrival will receive a full refund. Within 14 days, the first night is non-refundable. We strongly recommend travel insurance.',
  },
  {
    question: 'Do you have parking?',
    answer: 'Yes — we have complimentary private parking for all guests within the estate grounds. EV charging points are available.',
  },
  {
    question: 'Is WiFi available?',
    answer: 'Yes, complimentary high-speed WiFi is available throughout the hotel and all bedrooms. That said, we do gently encourage a digital detox — the glen is rather better than anything on a screen.',
  },
  {
    question: 'Can I book a private dining experience?',
    answer: 'Absolutely. We offer private dining in the library for 2–12 guests, with a bespoke menu designed around your preferences by Chef Finlay Ross. Please enquire at least 72 hours in advance.',
  },
  {
    question: 'How far are you from Edinburgh and Glasgow?',
    answer: 'We are approximately 1 hour 15 minutes from Edinburgh and 1 hour 30 minutes from Glasgow by car. Taxi transfers from Perth train station (25 minutes) are available by arrangement.',
  },
];

export const offers = [
  {
    slug: 'highland-escape',
    title: 'The Highland Escape',
    subtitle: 'Three nights from £195 per person per night',
    description: 'Three nights in your choice of Classic or Deluxe room, full Scottish breakfast each morning, a three-course dinner on one evening, and a guided estate walk with our ranger.',
    validFrom: '2025-01-01',
    validTo: '2025-12-31',
    inclusions: ['3 nights accommodation', 'Full Scottish breakfast daily', '1 x three-course dinner', 'Guided estate walk', 'Welcome dram on arrival'],
    image: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?w=800&q=80',
    tag: 'Best Value',
  },
  {
    slug: 'hogmanay-package',
    title: 'Hogmanay at Craigmore',
    subtitle: 'From £895 per room for two nights',
    description: 'Welcome 2025 in the most spectacular highland fashion. Candlelit Hogmanay dinner, a midnight dram of rare whisky, piping at the stroke of twelve, and a late breakfast to ease into the new year.',
    validFrom: '2024-12-30',
    validTo: '2025-01-02',
    inclusions: ['2 nights accommodation', 'Hogmanay dinner', 'Midnight whisky dram', 'Piping ceremony', 'New Year\'s breakfast'],
    image: 'https://images.pexels.com/photos/1569003/pexels-photo-1569003.jpeg?w=800&q=80',
    tag: 'Seasonal',
  },
  {
    slug: 'autumn-stalking-weekend',
    title: 'Autumn Stalking Weekend',
    subtitle: 'From £1,200 per rifle for two nights',
    description: 'Two nights in a Deluxe room with early breakfast, full day on the hill with our head stalker, venison from your stag prepared for the journey home, and a celebratory dinner.',
    validFrom: '2024-09-01',
    validTo: '2024-11-30',
    inclusions: ['2 nights accommodation', 'Full day stalking with head stalker', 'Early breakfast both days', 'Larder and venison preparation', 'Celebratory dinner'],
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?w=800&q=80',
    tag: 'Field Sports',
  },
];

export const journalPosts = [
  {
    slug: 'autumn-in-perthshire',
    title: 'Autumn in Perthshire: A Season Like No Other',
    category: 'Local Guides',
    author: 'Catriona Mackenzie',
    publishedAt: '2024-10-15',
    readingTime: '6 min read',
    excerpt: 'The larches turn gold, the stags roar across the hill, and Craigmore reaches its full expression. Our guide to the most extraordinary season in the Scottish highlands.',
    image: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?w=800&q=80',
    body: 'Autumn arrives in Perthshire with a particular drama...',
  },
  {
    slug: 'distillery-trail-guide',
    title: 'The Craigmore Distillery Trail: Six Malts Worth the Drive',
    category: 'Food & Drink',
    author: 'Alasdair Mackenzie',
    publishedAt: '2024-09-08',
    readingTime: '8 min read',
    excerpt: 'From Edradour to Blair Athol, we\'ve mapped the finest distillery visits within an hour of Craigmore — with tasting notes and the honest truth about which ones are worth your afternoon.',
    image: 'https://images.pexels.com/photos/3407777/pexels-photo-3407777.jpeg?w=800&q=80',
    body: 'Perthshire sits at the edge of the Highland whisky country...',
  },
  {
    slug: 'red-deer-season',
    title: 'The Rut: Walking the Hill in Red Deer Season',
    category: 'Wildlife',
    author: 'Duncan Fraser',
    publishedAt: '2024-10-01',
    readingTime: '5 min read',
    excerpt: 'Head stalker Duncan Fraser on the spectacle of the red deer rut — the roaring, the fighting, the extraordinary theatre that plays out on our hill every October.',
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?w=800&q=80',
    body: 'October on the hill is unlike anything else in the calendar...',
  },
  {
    slug: 'chefs-garden',
    title: 'The Kitchen Garden: How Finlay Cooks the Estate',
    category: 'Food & Drink',
    author: 'Finlay Ross',
    publishedAt: '2024-08-20',
    readingTime: '7 min read',
    excerpt: 'Our head chef walks us through the walled garden in late summer — and explains how a four-acre kitchen garden shapes every menu at Craigmore throughout the year.',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?w=800&q=80',
    body: 'Every dish at Craigmore begins with a walk...',
  },
];
